server:
  port: 8080

jasypt:
  encryptor:
    password: liky

spring:
  datasource:
    url: ENC(J8Tbb/e6TM2k23bwAk0thVqUxXtIPKX1MEEFCK/dFcLy/Kv/IjYWULL00Nq2rJtb3jM2yvqju43IZjV25v9xwV5wP5ZWqT2DMDB6HI4ZwS6M4DOiqfe61QBDy0hHUTeDKnOgkLx7dt4kmxmsCwQSs1ZnTP4NoZzX)
    username: ENC(XhtJ+uDBUCJpaOgBw1yEvg==)
    password: ENC(EWi1niPjasF9R/cgtDI1/g==)
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

# MinIO对象存储相关配置
#minio:
#  endpoint: oss-cn-beijing.aliyuncs.com           #MinIO服务所在地址
#  bucketName:                                     #存储桶名称
#  accessKey: LTAI4G1rTK2wYC6cuTYN9vW5             #访问的key
#  secretKey: 9mUbPO5JhFGzRHjsmAYi7lC5wWmAFQ       #访问的秘钥

## OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com                                          # oss对外服务的访问域名
    accessKeyId: ENC(7J1+z3FnruFAB21/gtMFeaOQ2Vs7wpbDgjwKUAIS3HNHCd2FKKvVKg==)     # 访问身份验证中用到用户标识
    accessKeySecret: ENC(PEVOktSF/QMYuYuYa6MhJF8dBWOe9gNh1Jukmw/5+ttOD1Go+amZfA==) # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: ENC(N3fi+v2iYYMTiBeGvSNJXL3tymt99wwy)                              # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://localhost:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: mall/images/ # 上传文件夹路径前缀

