server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://39.100.149.36:3305/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mabatis:
  mapper-locations:
    - classpath: mapper/*.xml
    - classpath*: com/**/mapper/*.xml
